const MODEL="gemini-3.5-flash-lite",GEMINI_URL=`https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent`,SESSION_DAYS=30;
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json;charset=utf-8","cache-control":"no-store",...headers}})}
function cleanJson(t){return JSON.parse((t||"").trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"") )}
function hex(a){return [...a].map(b=>b.toString(16).padStart(2,"0")).join("")}
function randomHex(n=32){const a=new Uint8Array(n);crypto.getRandomValues(a);return hex(a)}
async function sha256(v){return hex(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v))))}
async function hashPassword(password,salt=randomHex(16)){const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]),bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt:new TextEncoder().encode(salt),iterations:100000},k,256);return{salt,hash:hex(new Uint8Array(bits))}}
function safeEqual(a,b){if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
function cookie(req,name){for(const p of (req.headers.get("cookie")||"").split(";")){const[k,...v]=p.trim().split("=");if(k===name)return decodeURIComponent(v.join("="))}return""}
function sessionCookie(token,age=SESSION_DAYS*86400){return`ef_session=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${age}`}
function validEmail(v){return/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)&&v.length<=254}
function validKey(v){return/^ef_[A-Za-z0-9_.:-]{1,120}$/.test(v)&&v!=="ef_sync_id"}
async function currentUser(req,env){const token=cookie(req,"ef_session");if(!token||!env.DB)return null;return await env.DB.prepare("SELECT u.id,u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?").bind(await sha256(token),Date.now()).first()||null}
async function requireUser(req,env){const u=await currentUser(req,env);if(!u)throw Object.assign(new Error("Please sign in first."),{status:401});return u}
async function gemini(env,parts,jsonMode=true){if(!env.GEMINI_API_KEY)throw new Error("GEMINI_API_KEY is not configured.");const body={contents:[{role:"user",parts}],generationConfig:{temperature:.35}};if(jsonMode)body.generationConfig.responseMimeType="application/json";const r=await fetch(GEMINI_URL,{method:"POST",headers:{"content-type":"application/json","x-goog-api-key":env.GEMINI_API_KEY},body:JSON.stringify(body)}),out=await r.json();if(!r.ok)throw new Error(out?.error?.message||"Gemini request failed.");const t=out?.candidates?.[0]?.content?.parts?.map(p=>p.text||"").join("")||"";return jsonMode?cleanJson(t):t}
function filePart(f){if(!f?.data)return null;let mime=f.mime_type||"application/octet-stream";if(f.name?.toLowerCase().endsWith(".pdf"))mime="application/pdf";if(f.name?.match(/\.(txt|md|csv)$/i))mime="text/plain";if(f.name?.match(/\.(png|jpg|jpeg|webp|heic|heif)$/i))mime=f.mime_type||"image/jpeg";return{inline_data:{mime_type:mime,data:f.data}}}
async function handleApi(req,env){const u=new URL(req.url);try{
 if(u.pathname==="/api/health")return json({ok:true,model:MODEL});
 if(u.pathname==="/api/auth/me")return json({user:await currentUser(req,env)});
 if(req.method!=="POST")return json({error:"POST required"},405);const b=await req.json().catch(()=>({}));
 if(u.pathname==="/api/auth/signup"){if(!env.DB)return json({error:"Account database is not configured."},500);const email=String(b.email||"").trim().toLowerCase(),password=String(b.password||"");if(!validEmail(email))return json({error:"Enter a valid email address."},400);if(password.length<10||password.length>128)return json({error:"Password must be 10–128 characters."},400);if(await env.DB.prepare("SELECT id FROM users WHERE email=?").bind(email).first())return json({error:"An account with that email already exists."},409);const id=crypto.randomUUID(),now=Date.now(),p=await hashPassword(password);await env.DB.prepare("INSERT INTO users(id,email,password_hash,password_salt,created_at) VALUES(?,?,?,?,?)").bind(id,email,p.hash,p.salt,now).run();const token=randomHex();await env.DB.prepare("INSERT INTO sessions(token_hash,user_id,created_at,expires_at) VALUES(?,?,?,?)").bind(await sha256(token),id,now,now+SESSION_DAYS*86400000).run();return json({user:{id,email},is_new:true},201,{"set-cookie":sessionCookie(token)})}
 if(u.pathname==="/api/auth/signin"){const email=String(b.email||"").trim().toLowerCase(),password=String(b.password||""),row=await env.DB.prepare("SELECT id,email,password_hash,password_salt FROM users WHERE email=?").bind(email).first(),p=await hashPassword(password,row?.password_salt||"invalid-account-salt");if(!row||!safeEqual(p.hash,row.password_hash))return json({error:"Email or password is incorrect."},401);const token=randomHex(),now=Date.now();await env.DB.prepare("INSERT INTO sessions(token_hash,user_id,created_at,expires_at) VALUES(?,?,?,?)").bind(await sha256(token),row.id,now,now+SESSION_DAYS*86400000).run();await env.DB.prepare("DELETE FROM sessions WHERE expires_at<=?").bind(now).run();return json({user:{id:row.id,email:row.email}},200,{"set-cookie":sessionCookie(token)})}
 if(u.pathname==="/api/auth/signout"){const token=cookie(req,"ef_session");if(token&&env.DB)await env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await sha256(token)).run();return json({ok:true},200,{"set-cookie":sessionCookie("",0)})}
 if(u.pathname==="/api/data/list"){const user=await requireUser(req,env),r=await env.DB.prepare("SELECT data_key,data,updated_at FROM user_data WHERE user_id=? ORDER BY updated_at").bind(user.id).all();return json({items:r.results||[]})}
 if(u.pathname==="/api/data/set"){const user=await requireUser(req,env),key=String(b.data_key||""),data=String(b.data??"");if(!validKey(key))return json({error:"Invalid data key."},400);if(data.length>200000)return json({error:"Saved item is too large."},413);const now=Date.now();await env.DB.prepare("INSERT INTO user_data(user_id,data_key,data,updated_at) VALUES(?,?,?,?) ON CONFLICT(user_id,data_key) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at").bind(user.id,key,data,now).run();return json({ok:true,updated_at:now})}
 if(u.pathname==="/api/data/import"){const user=await requireUser(req,env),items=Array.isArray(b.items)?b.items:[];if(items.length>100)return json({error:"Too many saved items."},413);const q=[],now=Date.now();for(const i of items){const key=String(i?.data_key||""),data=String(i?.data??"");if(validKey(key)&&data.length<=200000)q.push(env.DB.prepare("INSERT INTO user_data(user_id,data_key,data,updated_at) VALUES(?,?,?,?) ON CONFLICT(user_id,data_key) DO NOTHING").bind(user.id,key,data,now))}if(q.length)await env.DB.batch(q);return json({ok:true,imported:q.length})}
 if(u.pathname==="/api/data/delete"){const user=await requireUser(req,env),key=String(b.data_key||"");if(!validKey(key))return json({error:"Invalid data key."},400);await env.DB.prepare("DELETE FROM user_data WHERE user_id=? AND data_key=?").bind(user.id,key).run();return json({ok:true})}
 if(u.pathname.startsWith("/api/sync/"))return json({error:"Sync codes have been retired. Sign in to sync your work."},410);
 if(u.pathname==="/api/analyze-syllabus"){const course=b.course||{},text=String(b.text||"").trim(),parts=[{text:`Build a study profile for ${course.name||"this nursing and health sciences course"} from ONLY the supplied course material. Do not add outside topics. Organize every topic under the chapter, unit, or module where it belongs; do not repeat a topic in multiple places.\nReturn ONLY JSON:\n{"chapters":[{"name":"explicit chapter/unit/module name","topics":["specific source-supported topic"]}],"assessments":["explicit exams/quizzes/projects"],"notes":"concise study emphasis based only on the material","course_source":"compact normalized source text preserving the actual chapter structure, topics, scope, formulas/methods and learning objectives needed to generate future practice"}\nThe course_source must not invent anything and should preserve enough detail to strictly constrain future questions.`}];if(text)parts.push({text:"PASTED COURSE MATERIAL:\n"+text.slice(0,70000)});const fp=filePart(b.file);if(fp)parts.push(fp);if(!text&&!fp)return json({error:"Upload or paste course material first."},400);const profile=await gemini(env,parts,true);profile.raw_material=(profile.course_source||text||"").slice(0,60000);return json({profile})}
 if(u.pathname==="/api/generate-problem"){const c=b.course||{},p=b.profile||{},d=String(b.difficulty||"Mixed"),raw=String(p.raw_material||""),focus=Array.isArray(b.focus)?b.focus.map(String).filter(Boolean).slice(0,30):[];if(!raw)return json({error:"No saved syllabus source is available."},400);const focusRule=focus.length?`\nSELECTED TOPICS ONLY: The problem must specifically test one or more of these selected syllabus topics and no unselected topic: ${JSON.stringify(focus)}`:"\nTOPIC SELECTION: No specific topic was selected, so choose any topic supported by the saved course source.";return json(await gemini(env,[{text:`Create ONE original FREE-RESPONSE engineering practice problem for ${c.name||"the course"}.\nSTRICT SOURCE RULE: use ONLY topics, methods, terminology, scope, formulas, and learning objectives supported by SAVED COURSE SOURCE below. No multiple choice. Do not import adjacent topics from general engineering knowledge.${focusRule}\nDifficulty: ${d}\nSAVED COURSE SOURCE:\n${raw.slice(0,55000)}\nReturn ONLY JSON:\n{"topic":"source-supported selected topic","difficulty":"Easy|Medium|Hard","problem":"complete free-response problem with all needed values, units, and assumptions","hint":"helpful hint without revealing the answer","solution":"fully worked reference solution","final_answer":"concise final result","grading_criteria":["required elements"]}`}],true))}
 if(u.pathname==="/api/check-answer"){const p=b.problem||{},a=String(b.answer||"").trim();if(!p.problem||!a)return json({error:"Problem and answer are required."},400);return json(await gemini(env,[{text:`Grade this free-response nursing and health sciences response. Accept alternate valid methods if they are correct.\nPROBLEM:\n${p.problem}\nREFERENCE SOLUTION:\n${p.solution||""}\nGRADING CRITERIA:\n${JSON.stringify(p.grading_criteria||[])}\nSTUDENT RESPONSE:\n${a}\nReturn ONLY JSON:\n{"correct":true,"feedback":"specific concise feedback","correct_approach":"brief corrected approach or confirmation"}`}],true))}
 if(u.pathname==="/api/analyze-work"){const c=b.course||{},p=b.profile||{},problem=String(b.problem_text||""),ref=String(b.reference_solution||""),img=b.image;if(!p.raw_material||!problem||!img?.data)return json({error:"Syllabus context, problem, and image are required."},400);return json(await gemini(env,[{text:`Analyze the student's handwritten nursing and health sciences work for ${c.name||"the selected course"}.\nSTRICT COURSE SCOPE: judge methods using ONLY the saved course source plus the stated problem. Find the FIRST meaningful mathematical, physical, sign, unit, equation, or reasoning error. If the work is correct, say so. If handwriting is unreadable, identify what cannot be read rather than guessing.\nSAVED COURSE SOURCE:\n${String(p.raw_material).slice(0,45000)}\nPROBLEM:\n${problem}\nREFERENCE SOLUTION IF AVAILABLE:\n${ref.slice(0,10000)}\nReturn ONLY JSON:\n{"overall_status":"Correct|Mostly correct|Needs revision|Unreadable","summary":"brief overall assessment","what_you_did_right":["specific correct steps"],"first_error":"first error or empty string","why_wrong":"why it fails","corrected_step":"corrected version","next_steps":["what to do next"],"review_concepts":["only source-supported concepts"]}`},{inline_data:{mime_type:img.mime_type||"image/jpeg",data:img.data}}],true))}
 return json({error:"Unknown API route"},404)
}catch(e){return json({error:e.message||String(e)},e.status||500)}}
export default{async fetch(req,env){if(new URL(req.url).pathname.startsWith("/api/"))return handleApi(req,env);return env.ASSETS.fetch(req)}};
